# Generated by Django 6.0.7 on 2026-07-20 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable internal identifier used by the API and payment system.', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('badge', models.CharField(blank=True, help_text='Optional customer-facing symbol, such as a trophy or crown.', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('grace_period_days', models.PositiveIntegerField(default=3)),
                ('price_naira', models.DecimalField(decimal_places=2, help_text='Customer-facing price in Nigerian naira.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_naira'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='plan_duration_days_greater_than_zero'), models.CheckConstraint(condition=models.Q(('price_naira__gte', 0)), name='plan_price_naira_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(choices=[('paystack', 'Paystack'), ('complimentary', 'Complimentary'), ('admin', 'Admin'), ('gift', 'Gift'), ('referral', 'Referral Reward'), ('loyalty', 'Loyalty Reward')], default='paystack', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifted_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscription_user_status_idx')],
            },
        ),
    ]
