# Generated by Django 6.0.7 on 2026-07-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_locked', models.BooleanField(default=False, help_text='Lock after the first successful payment to prevent unauthorised regional price switching.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code, such as NG or GH.', max_length=2, unique=True)),
                ('default_currency', models.CharField(help_text='ISO 4217 currency code, such as NGN or GHS.', max_length=3)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('payment_provider', models.CharField(default='paystack', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('checkout_enabled', models.BooleanField(default=False, help_text='Controls whether customers in this country can currently pay.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO 4217 currency code.', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country__display_order', 'plan__display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='plan',
            name='plan_price_naira_not_negative',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_profiles', to='subscriptions.country'),
        ),
        migrations.AddField(
            model_name='planprice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_prices', to='subscriptions.country'),
        ),
        migrations.AddField(
            model_name='planprice',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.plan'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_naira',
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'country', 'currency'), name='unique_plan_country_currency_price'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='plan_price_amount_not_negative'),
        ),
    ]
