# Generated by Django 6.0.7 on 2026-07-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('opted_in', 'Opted in'), ('opted_out', 'Opted out')], default='opted_out', max_length=16)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('notice_version', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('terms_of_use', 'Terms of Use'), ('privacy_policy', 'Privacy Policy'), ('refund_policy', 'Refund and Subscription Policy'), ('disclaimer', 'Disclaimer and Responsible Use Policy'), ('cookie_policy', 'Cookie Policy'), ('copyright_policy', 'Copyright and Intellectual Property Policy'), ('acceptable_use', 'Acceptable Use Policy'), ('risk_disclosure', 'Risk Disclosure Statement'), ('responsible_gambling', 'Responsible Gambling Statement'), ('aml_kyc', 'AML/KYC Statement'), ('methodology', 'Prediction Methodology')], help_text='Which policy this version belongs to.', max_length=32)),
                ('version', models.CharField(help_text="Human-readable version, e.g. '1.0'.", max_length=20)),
                ('effective_date', models.DateField(help_text='The date this version takes effect / was published.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current required version for its policy_type. Only one version per policy_type should be active at a time.')),
                ('is_material_change', models.BooleanField(default=False, help_text='Whether this version introduces changes significant enough to require existing users to re-accept.')),
                ('content_hash', models.CharField(blank=True, help_text='Optional integrity hash of the published content for this version.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['policy_type', '-effective_date'],
                'indexes': [models.Index(fields=['policy_type', 'is_active'], name='legal_polic_policy__6dce78_idx')],
                'constraints': [models.UniqueConstraint(fields=('policy_type', 'version'), name='unique_policy_type_version')],
            },
        ),
        migrations.CreateModel(
            name='UserPolicyAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_source', models.CharField(choices=[('web_signup', 'Web signup'), ('mobile_signup', 'Mobile signup'), ('checkout', 'Checkout'), ('policy_update', 'Policy update reacceptance'), ('admin', 'Admin action')], default='web_signup', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.policydocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'policy'], name='legal_userp_user_id_ae9410_idx'), models.Index(fields=['policy', 'accepted_at'], name='legal_userp_policy__022d8d_idx')],
            },
        ),
    ]
