# Generated by Django 6.0.7 on 2026-07-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_seed_initial_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocument',
            name='change_summary',
            field=models.TextField(blank=True, help_text='Human-readable summary of what changed in this version, for the public change log.'),
        ),
    ]
