# Generated by Django 6.0.7 on 2026-07-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='paystack', max_length=30)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('processing_status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('invalid_signature', 'Invalid Signature')], db_index=True, max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(default='paystack', max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=30)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
